export { AmendmentStudio } from './AmendmentStudio';
export { AmendmentProjectsList } from './AmendmentProjectsList';
export { OfficeActionNavigator } from './OfficeActionNavigator';
export { DraftingWorkspace } from './DraftingWorkspace';
export { AIAssistantPanel } from './AIAssistantPanel';
export { AmendmentFileHistory } from './AmendmentFileHistory';
export { ArgumentsTab } from './ArgumentsTab';
export { ClaimsDocumentPreview } from './ClaimsDocumentPreview';
export { RemarksDocumentPreview } from './RemarksDocumentPreview'; 