name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NEXT_PUBLIC_SENTRY_DSN: ''

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Build Next.js app
        run: npm run build
        env:
          CI: 'true'

      - name: Prisma migrate smoke test (SQLite)
        run: |
          export DATABASE_URL="file:./ci-test.db"
          npx prisma migrate deploy

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Lighthouse audit (report only)
        if: github.event_name == 'pull_request'
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'http://localhost:3000'
          budgetPath: '.github/lighthouse-budget.json'
          uploadArtifacts: true
          configPath: '.github/lighthouserc.json'
